version: '2.1'

services:

  # Service definition for Consul cluster with a minimum of 3 nodes.
  # For local development we use Compose v2 so that we have an automatically
  # created user-defined network and internal DNS for the name "consul".
  # Nodes will use Docker DNS for the service (passed in via the CONSUL
  # env var) to find each other and bootstrap the cluster.
  consul:
    build: .
    restart: always
    mem_limit: 128m
    ports:
        - 8500
    environment:
      - CONSUL=consul
      - CONSUL_DATACENTER_NAME=dc1
    command: >
      /usr/local/bin/containerpilot
