version: '2.1'

services:

  # Service definition for Consul cluster with a minimum of 3 nodes.
  # For local development we use Compose v2 so that we have an automatically
  # created user-defined network and internal DNS for the name "consul".
  # Nodes will use Docker DNS for the service (passed in via the CONSUL
  # env var) to find each other and bootstrap the cluster.
  consul1:
    build: .
    image: autopilotpattern/consul:${TAG:-latest}
    restart: always
    mem_limit: 128m
    ports:
        - 8500
    environment:
      - CONSUL=consul1
      - CONSUL_DATACENTER_NAME=dc1
    command: >
      /usr/local/bin/containerpilot

  # The following service block defines a nearly-identical deployment in a
  # fictional second datacenter. This can be used to test multi-datacenter
  # behavior in Consul.
  # NOTE: CONSUL_RETRY_JOIN_WAN *must* be a valid HCL list,
  # e.g.:
  #    "1.1.1.1"
  # or
  #    "1.1.1.1","2.2.2.2"

  consul2:
    image: autopilotpattern/consul:${TAG:-latest}
    restart: always
    mem_limit: 128m
    ports:
        - 8500
    environment:
      - CONSUL=consul2
      - CONSUL_DATACENTER_NAME=dc2
      - CONSUL_RETRY_JOIN_WAN="consul1"
    command: >
      /usr/local/bin/containerpilot
    links:
      - consul1
